name: Publish Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Extension version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Update version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      - name: Build
        run: npm run dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gemini-control-${{ github.event.inputs.version }}.zip
          tag_name: ${{ github.event.inputs.version }}